# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Finnish spellchecker"
fi = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Finnish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
fi = "TRANSLATE: A spellchecker for Finnish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.fi"

[windows]
system_product_code = "{94E8FE18-0CBD-4171-966A-4F9B7F65D7C3}_is1"
legacy_product_codes = [
    { value = "65E51ACB-AF3D-4EE2-825C-326A58332AB6", kind = "nsis" },
    { value = "910AC24F-E8C9-410C-A670-CC9A641DD3C2", kind = "nsis" }
]

[package.speller]
name = "Finnish"
version = "0.1.1"

[package.grammar]
name = "Finnish"
version = "0.1.0"

[package.tts-textproc]
name = "Finnish"
version = "0.1.0"

[package.hyphenator]
name = "Finnish"
version = "0.1.0"
